Traceback (most recent call last):
  File "/lustre06/project/6003138/rezvank/5_model/baseline.py", line 104, in <module>
    X = np.array([X[i] for i in range(len(X))])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (10375,) + inhomogeneous part.
